Add new openshift-ansible test types and profiles in the generator
openshift/ci-operator-prowgen pull request #36
Opened 2018-10-12 14:59 UTC by vrutkovs

Verified that this can generate GCP logging, custom aws template and GCP major upgrade job

2018-10-12 14:59 UTC, vrutkovs commented on cmd/ci-operator-prowgen/main.go
> +	var previousVersion string
not entirely sure about those - should I copy config string here or just make `conf` visible later on?

2018-10-15 10:23 UTC, bbguimaraes requested changes

2018-10-15 10:23 UTC, bbguimaraes commented on cmd/ci-operator-prowgen/main.go
> +	}
As you said above, since these are specific to a single type of test, remove the local variables and check the field directly:

```go
if conf := test.OpenshiftAnsibleUpgradeClusterTestConfiguration; conf != nil {
    // use conf.PreviousVersion, etc.
}
```

2018-10-15 11:09 UTC, vrutkovs commented on cmd/ci-operator-prowgen/main.go
> +	}
Done

2018-10-15 11:48 UTC, bbguimaraes commented
/lgtm

2018-10-15 11:51 UTC, merged